name: "Pull Request / Push Build"
on:
  - push
  - pull_request
jobs:
  build:
    name: JVM build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11 ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install JDK {{ matrix.java }}
        uses: joschi/setup-jdk@v1.0.0
        with:
          java-version: openjdk${{ matrix.java }}
      - name: Build with Maven
        run: |
          LANG=en_US mvn -V -B clean install
      - name: Zip Artifacts
        run: |
          zip -R artifacts-jvm${{ matrix.java }}.zip 'surefire-reports/*' 'failsafe-reports/*'
      - uses: actions/upload-artifact@v1
        with:
          name: ci-artifacts
          path: artifacts-jvm${{ matrix.java }}.zip
  native-build:
    name: Native build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11 ]
    needs:
      - build
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install JDK {{ matrix.java }}
        uses: joschi/setup-jdk@v1.0.0
        with:
          java-version: openjdk${{ matrix.java }}
      - name: Build with Maven
        run: |
          mvn -V -B clean install -Dnative \
            -Dquarkus.native.container-build=true \
            -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java${{ matrix.java }}
      - name: Zip Artifacts
        run: |
          zip -R artifacts-native${{ matrix.java }}.zip 'surefire-reports/*' 'failsafe-reports/*'
      - uses: actions/upload-artifact@v1
        with:
          name: ci-artifacts
          path: artifacts-native${{ matrix.java }}.zip
